### ISSUE TITLE
codes for osr task

### ISSUE THREAD

**Issue by Mickey-Boy** [taslimisina/osr-ood-ad-methods#1]
It's really a interesting work to construct such a union framework for osr, ood and ad. Thanks for your contribution to this area. When will the codes for osr part be released.

**Comment by taslimisina** [comment]
Thank you for your comment Mickey-Boy. I can't give a date yet, but we are still working on it.

**Comment by LuckMonkeys** [comment]
Hello, any progress on the OSR task code release?
